#ifndef WINDOWS_H
#define WINDOWS_H

#define WINDOW_HOME 0
#define WINDOW_GAME 1
#define WINDOW_PROMPT_SAVE 2
#define WINDOW_PROMPT_RANKING 3
#define WINDOW_ENDGAME_RANKING 4
#define WINDOW_PROMPT_EXIT 5
#define WINDOW_PROMPT_NEW 6

#endif